on:
  push:
    branches:
    - '*'
    - '!badges'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install
      
      - name: Test with pytest
        run: |
          pipenv run coverage run --omit '*/virtualenvs/*' -m pytest 

      - name: Make the coverage badge
        run: |
          pipenv run python3 badge.py
      
      - name: Upload to repo
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git add *
          git commit -m "update the badge"
          git push